#!/system/bin/sh

echo "tweaks"
echo 5 > /sys/devices/system/cpu/cpu0/cpufreq/hotplug_plus_one_core

#echo "1" > /proc/sys/kernel/sched_child_runs_first

#echo 2 > /sys/devices/system/cpu/sched_mc_power_savings

echo 2048 > /proc/sys/fs/nr_open

#echo "128" > /sys/devices/virtual/bdi/default/read_ahead_kb

#echo 0 > /sys/kernel/printk_mode/printk_mode
#echo 0 > /sys/kernel/logger_mode/logger_mode

#echo 2048 > /proc/sys/kernel/random/read_wakeup_threshold
#echo 1024 > /proc/sys/kernel/random/write_wakeup_threshold


chmod 666 /sys/module/lowmemorykiller/parameters/minfree
echo "4096,8192,32768,49152,65536,131072" > /sys/module/lowmemorykiller/parameters/minfree


echo 1 > /sys/devices/platform/s5p-mipi-dsim.1/lcd/panel/mdnie/tuning
echo "CUSTOM1" > /sys/devices/platform/s5p-mipi-dsim.1/lcd/panel/mdnie/tuning
sleep 30;
echo "CORRECT" > /sys/devices/platform/s5p-mipi-dsim.1/lcd/panel/mdnie/tuning_correction
