#!/system/bin/sh

echo "Memory management tweaks"
echo "0" > /proc/sys/vm/swappiness
#echo "0" > /proc/sys/vm/overcommit_memory
echo "0" > /proc/sys/vm/oom_dump_tasks
echo "2000" > /proc/sys/vm/dirty_expire_centisecs
echo "3000" > /proc/sys/vm/dirty_writeback_centisecs
echo "0" > /proc/sys/vm/panic_on_oom
#echo "10" > /proc/sys/vm/vfs_cache_pressure


echo "Kernel tweaks"
echo "0" > /proc/sys/kernel/panic_on_oops
echo "1" > /proc/sys/kernel/sched_child_runs_first

sleep 60;

#logcat >> /sdcard/lg.txt


echo 0 > /sys/kernel/logger_mode/logger_mode
echo 0 > /sys/kernel/printk_mode/printk_mode

